/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import control.ServoControl;
import model.ServoModel;

/**
 *
 * @author drew
 */
public class Servo extends javax.swing.JPanel {

    private ServoModel modelData;
    /**
     * Creates new form Servo
     */
    public Servo() {
        initComponents();
    }
    boolean done = false;
    public void setServoModel(ServoModel model) {
        modelData = model;
        ServoNameLabel.setText(modelData.getName());
        ServoSlider.setMinimum(modelData.getMin());
        ServoSlider.setMaximum(modelData.getMax());
        ServoSlider.setValue(modelData.getCurrent());
        System.out.println("Current" + modelData.getCurrent());
        labelServoVal.setText(String.valueOf(modelData.getCurrent()));
        ServoSlider.setMajorTickSpacing(5);
        ServoSlider.updateUI();
        ServoSlider.repaint();
        done = true;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        ServoSlider = new javax.swing.JSlider();
        ServoNameLabel = new javax.swing.JLabel();
        labelServoVal = new javax.swing.JLabel();
        minCalibrated = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        minValField = new javax.swing.JLabel();
        maxValField = new javax.swing.JLabel();
        maxCalibrated = new javax.swing.JCheckBox();

        jCheckBox1.setText("jCheckBox1");

        ServoSlider.setMajorTickSpacing(5);
        ServoSlider.setMaximum(4);
        ServoSlider.setMinimum(-150);
        ServoSlider.setPaintTicks(true);
        ServoSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ServoSliderStateChanged(evt);
            }
        });

        ServoNameLabel.setText("Left Elbow");

        labelServoVal.setText(String.valueOf(ServoSlider.getValue()));

        minCalibrated.setText("Calibrated");

        jLabel1.setText("min:");

        jLabel2.setText("max:");

        minValField.setText("jLabel3");

        maxValField.setText("jLabel4");

        maxCalibrated.setText("Calibrated");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ServoNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ServoSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelServoVal)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minValField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxValField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minCalibrated)
                    .addComponent(maxCalibrated))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ServoNameLabel)
                    .addComponent(labelServoVal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ServoSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(minValField)
                            .addComponent(minCalibrated))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(maxValField)
                            .addComponent(maxCalibrated))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ServoSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ServoSliderStateChanged
        // TODO add your handling code here:
        if (done == true){
            //labelServoVal.setText(String.valueOf(modelData.getCurrent()));
            //modelData.setCurrent(ServoSlider.getValue());
            //labelServoVal.setText(String.valueOf(ServoSlider.getValue()));
            int val = ServoSlider.getValue();
            modelData.setCurrent(val);
            labelServoVal.setText(String.valueOf(val));
            System.out.println(modelData.getCurrent());
            
            ServoControl.getServoControl().setServo(modelData);
        }
    }//GEN-LAST:event_ServoSliderStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ServoNameLabel;
    private javax.swing.JSlider ServoSlider;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelServoVal;
    private javax.swing.JCheckBox maxCalibrated;
    private javax.swing.JLabel maxValField;
    private javax.swing.JCheckBox minCalibrated;
    private javax.swing.JLabel minValField;
    // End of variables declaration//GEN-END:variables
}
